---
- name: Deploy DefectDojo on GCP
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Include Docker role
      include_role:
        name: docker

    - name: Include System role (swap + kernel tuning)
      include_role:
        name: security

    - name: Include DefectDojo deployment role
      include_role:
        name: security-suite
